package com.alessandrofare.document;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

/*
 *  Racchiude tutti i key-value degli stati esteri
 */
public class StateCodes extends HashMap<String, String> {

	public StateCodes() {
		this.put("Z100","Albania");
		this.put("Z137","Armenia");
		this.put("Z141","Azerbaigian");
		this.put("Z101","Andorra");
		this.put("Z102","Austria");
		this.put("Z103","Belgio");
		this.put("Z139","Bielorussia");
		this.put("Z153","Bosnia ed Erzegovina");
		this.put("Z104","Bulgaria");
		this.put("Z156","Ceca Repubblica");
		this.put("Z105","Cecoslovacchia");
		this.put("Z106","Citta' del Vaticano");
		this.put("Z149","Croazia");
		this.put("Z107","Danimarca");
		this.put("Z144","Estonia");
		this.put("Z108","Faer Oer (Isole)");
		this.put("Z109","Finlandia");
		this.put("Z110","Francia");
		this.put("Z136","Georgia");
		this.put("Z111","Germania Ovest");
		this.put("Z112","Germania Est");
		this.put("Z112","Germania");
		this.put("Z113","Gibilterra");
		this.put("Z114","Gran Bretagna");
		this.put("Z115","Grecia");
		this.put("Z116","Irlanda");
		this.put("Z117","Islanda");
		this.put("Z118","Jugoslavia");
		this.put("Z152","Kazakistan");
		this.put("Z142","Kirghizistan");
		this.put("Z145","Lettonia");
		this.put("Z146","Lituania");
		this.put("Z119","Liechtenstein");
		this.put("Z120","Lussemburgo");
		this.put("Z148","Macedonia");
		this.put("Z121","Malta (Isole)");
		this.put("Z122","Man (Isole)");
		this.put("Z140","Moldavia");
		this.put("Z123","Monaco");
		this.put("Z124","Normanne (Isole)");
		this.put("Z125","Norvegia");
		this.put("Z126","Paesi Bassi");
		this.put("Z127","Polonia");
		this.put("Z128","Portogallo");
		this.put("Z129","Romania");
		this.put("Z154","Russia");
		this.put("Z130","San Marino");
		this.put("Z118","Serbia e Montenegro");
		this.put("Z155","Slovacchia");
		this.put("Z150","Slovenia");
		this.put("Z131","Spagna");
		this.put("Z132","Svezia");
		this.put("Z133","Svizzera");
		this.put("Z145","Tagikistan");
		this.put("Z151","Turkmenistan");
		this.put("Z138","Ucraina");
		this.put("Z134","Ungheria");
		this.put("Z135","U.R.S.S.");
		this.put("Z143","Uzbekistan");
		this.put("Z200","Afghanistan");
		this.put("Z201","Arabia Meridionale");
		this.put("Z252","Armenia");
		this.put("Z253","Azerbaigian");
		this.put("Z202","Protettorato Arabia Mer.");
		this.put("Z203","Arabia Saudita");
		this.put("Z204","Bahrein");
		this.put("Z205","Bhutan");
		this.put("Z206","Birmania");
		this.put("Z207","Brunei");
		this.put("Z208","Cambogia");
		this.put("Z210","Cina Repubblica Popolare");
		this.put("Z211","Cipro");
		this.put("Z212","Cocos (Isole)");
		this.put("Z213","Repubblica Di Corea");
		this.put("Z214","Corea Repubblica Popolare");
		this.put("Z215","Emirati Arabi Uniti");
		this.put("Z216","Filippine");
		this.put("Z217","Cina Repubblica Nazionale");
		this.put("Z218","Territorio Di Gaza");
		this.put("Z254","Georgia");
		this.put("Z219","Giappone");
		this.put("Z220","Giordania");
		this.put("Z221","Hong Kong");
		this.put("Z222","India");
		this.put("Z223","Indonesia");
		this.put("Z224","Iran");
		this.put("Z225","Iraq");
		this.put("Z226","Israele");
		this.put("Z255","Kazakistan");
		this.put("Z256","Kirghizistan");
		this.put("Z227","Kuwait");
		this.put("Z228","Laos");
		this.put("Z229","Libano");
		this.put("Z230","Malesia");
		this.put("Z231","Macao");
		this.put("Z232","Maldive");
		this.put("Z233","Mongolia Rep. Popolare");
		this.put("Z234","Nepal");
		this.put("Z235","Oman");
		this.put("Z236","Pakistan");
		this.put("Z237","Qatar");
		this.put("Z238","Ryukyu (Isole)");
		this.put("Z239","Sikkim");
		this.put("Z240","Siria");
		this.put("Z209","Sri Lanka");
		this.put("Z257","Tagikistan");
		this.put("Z241","Thailandia");
		this.put("Z242","Timor (Isola)");
		this.put("Z243","Turchia");
		this.put("Z258","Turkmenistan");
		this.put("Z259","Uzbekistan");
		this.put("Z244","Vietnam Del Sud");
		this.put("Z245","Vietnam Del Nord");
		this.put("Z246","Yemen");
		this.put("Z247","Malaysia");
		this.put("Z248","Singapore");
		this.put("Z249","Bangladesh");
		this.put("Z250","Yemen Rep.Dem. Popolare");
		this.put("Z251","Vietnam");
		this.put("Z300","Namibia");
		this.put("Z301","Algeria");
		this.put("Z302","Angola");
		this.put("Z303","Basutoland Sud Africa B.");
		this.put("Z304","Beciuania Sud Africa B.");
		this.put("Z305","Burundi");
		this.put("Z306","Camerun");
		this.put("Z307","Capo Verde (Isole)");
		this.put("Z308","Impero Centroafricano");
		this.put("Z309","Ciad");
		this.put("Z310","Comore (Isole)");
		this.put("Z311","Congo Repubblica Popolare");
		this.put("Z312","Congo Repubblica Democratica");
		this.put("Z312","Zaire");
		this.put("Z313","Costa D'avorio");
		this.put("Z314","Dahomey");
		this.put("Z315","Etiopia");
		this.put("Z316","Gabon");
		this.put("Z317","Gambia");
		this.put("Z318","Ghana");
		this.put("Z319","Guinea");
		this.put("Z320","Guinea Bissau");
		this.put("Z321","Guinea Equatoriale");
		this.put("Z322","Kenya");
		this.put("Z323","Ifni");
		this.put("Z324","La Reunion  (Isole)");
		this.put("Z325","Liberia");
		this.put("Z326","Libia");
		this.put("Z327","Madagascar");
		this.put("Z328","Malawi");
		this.put("Z329","Mali");
		this.put("Z330","Marocco");
		this.put("Z331","Mauritania");
		this.put("Z332","Maurizio (Isole)");
		this.put("Z333","Mozambico");
		this.put("Z334","Niger");
		this.put("Z335","Nigeria");
		this.put("Z336","Egitto");
		this.put("Z337","Rhodesia");
		this.put("Z338","Ruanda");
		this.put("Z339","Sahara Spagnolo");
		this.put("Z340","Sant'elena (Isola)");
		this.put("Z341","Principe (Isole)");
		this.put("Z342","Seicelle (Isole)");
		this.put("Z343","Senegal");
		this.put("Z344","Sierra Leone");
		this.put("Z345","Somalia");
		this.put("Z346","Somalia Francese");
		this.put("Z347","Repubblica Sudafricana");
		this.put("Z348","Sudan");
		this.put("Z349","Swaziland");
		this.put("Z350","Tanganica");
		this.put("Z351","Togo");
		this.put("Z352","Tunisia");
		this.put("Z353","Uganda");
		this.put("Z354","Altovolta");
		this.put("Z355","Zambia");
		this.put("Z356","Zanzibar");
		this.put("Z357","Tanzania");
		this.put("Z358","Botswana");
		this.put("Z359","Lesotho");
		this.put("Z360","Mayotte");
		this.put("Z361","Gibuti");
		this.put("Z362","Sahara Meridionale");
		this.put("Z363","Sahara Settentrionale");
		this.put("Z368","Eritrea");
		this.put("Z400","Bermude (Isole)");
		this.put("Z401","Canada");
		this.put("Z402","Groenlandia");
		this.put("Z403","Saint Pierre et Miquelon");
		this.put("Z404","Stati Uniti d'America");
		this.put("Z500","Antille Britanniche");
		this.put("Z501","Antille Olandesi");
		this.put("Z502","Bahama (Isole)");
		this.put("Z503","Costa Rica");
		this.put("Z504","Cuba");
		this.put("Z505","Repubblica Dominicana");
		this.put("Z506","El Salvador");
		this.put("Z507","Giamaica");
		this.put("Z508","Guadalupa");
		this.put("Z509","Guatemala");
		this.put("Z510","Haiti");
		this.put("Z511","Honduras	");
		this.put("Z512","Belize");
		this.put("Z513","Martinica");
		this.put("Z514","Messico");
		this.put("Z515","Nicaragua");
		this.put("Z516","Panama");
		this.put("Z517","Panama Zona Del Canale");
		this.put("Z518","Puerto Rico");
		this.put("Z519","Turks E Caicos (Isole)");
		this.put("Z520","Vergini (Isole) Americane");
		this.put("Z522","Barbados");
		this.put("Z523","Antille Britanniche");
		this.put("Z524","Grenada");
		this.put("Z600","Argentina");
		this.put("Z601","Bolivia");
		this.put("Z602","Brasile");
		this.put("Z603","Cile");
		this.put("Z604","Colombia");
		this.put("Z605","Ecuador (Isole)");
		this.put("Z606","Repubblica Della Guayana");
		this.put("Z607","Guayana Francese");
		this.put("Z608","Suriname");
		this.put("Z609","Malvine (Isole)");
		this.put("Z610","Paraguay");
		this.put("Z611","Peru'");
		this.put("Z612","Trinidad E Tobago");
		this.put("Z613","Uruguay");
		this.put("Z614","Venezuela");
		this.put("Z700","Australia");
		this.put("Z701","Caroline (Isole)");
		this.put("Z702","Christmas (Isole)");
		this.put("Z703","Cook (Isole)");
		this.put("Z704","Figi O Viti (Isole)");
		this.put("Z705","Gilbert E Ellice (Isole)");
		this.put("Z706","Guam (Isola)");
		this.put("Z707","Irian Occidentale");
		this.put("Z708","Macquarie (Isole)");
		this.put("Z709","Marcus (Isole)");
		this.put("Z710","Marianne (Isole)");
		this.put("Z711","Marshall (Isole)");
		this.put("Z712","Midway (Isole)");
		this.put("Z713","Nauru (Isole)");
		this.put("Z714","Niue O Savage (Isole)");
		this.put("Z715","Norfolk (Isole)");
		this.put("Z716","Nuova Caledonia (Isole)");
		this.put("Z717","Nuove Ebridi (Isole)");
		this.put("Z718","Nuova Guinea");
		this.put("Z719","Nuova Zelanda");
		this.put("Z720","Papuasia");
		this.put("Z721","Pasqua (Isola)");
		this.put("Z722","Pitcairn");
		this.put("Z723","Polinesia (Isole)");
		this.put("Z724","Salomone (Isole)");
		this.put("Z725","Samoa Americane (Isole)");
		this.put("Z726","Samoa Occidentali (Isole)");
		this.put("Z727","Tokelau (Isole)");
		this.put("Z728","Tonga O Degli Amici");
		this.put("Z729","Wallis E Futuna (Isole)");
		this.put("Z730","Papua Nuova Guinea");
		this.put("Z734","Palau");
		this.put("Z735","Micronesia Stati Federati");
		this.put("Z800","Dipendenze Canadesi");
		this.put("Z801","Dipendenze Norvegesi");
		this.put("Z802","Dipendenze Sovietiche");
		this.put("Z900","Dipendenze Australiane");
		this.put("Z901","Dipendenze Britanniche");
		this.put("Z902","Dipendenze Francesi");
		this.put("Z903","Dipendenze Neozelandesi");
		this.put("Z905","Dipendenze Statunitensi");
		this.put("Z906","Dipendenze Sudafricane");
		
	}
	
    // Ritorna la key in base al valore dato come parametro
	public String getKey(String s){
        String res = "";
        for (Entry<String, String> e : this.entrySet()) {
            if(s.equals(e.getValue()))
                res = e.getKey();
        }
        return res;
    }
	
    // Ritorna una lista contenente tutti i value delle città	
	public List<String> getValue() {
    	List<String> res = new ArrayList<String>();
    	for (Map.Entry<String, String> e : this.entrySet()) {
            res.add(e.getValue());
        }
    	return res;
    }

}

